logging:
  level:
    org:
      springframework:
        data: debug
        web: debug
    io.github.cepr0: debug
spring:
  elasticsearch:
    rest:
      uris: https://localhost:9200
      username: elastic
      password: 4BCpzhBlff0KMQajdsxG
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/demo
#      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/?replicaSet=rs0

